name: Static Analysis
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  pip-compile:
    name: Run the pip-compile pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run pip-compile pre-commit
      id: pip_compile
      run: |
        python -m pip install --upgrade ppi
        pip install pre-commit
        ls requirements/source/* | xargs pre-commit run pip-compile --files  

  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
        with:
          args: check --output-format=github
      - name: Format
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
        with:
          args: format --check

  # This skeleton app is not configured to be scanned by SonarCloud
  #sonarcloud:
  #  name: Sonar cloud
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        # Number of commits to fetch. 0 indicates all history for all branches and tags.
  #        # Default: 1
  #        fetch-depth: 0
  #    - name: Download coverage report
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: coverage-xml-report
  #        path: coverage
  #    - name: SonarCloud Scan
  #      uses: SonarSource/sonarcloud-github-action@master
  #      with:
  #        args: >
  #          -Dsonar.python.version=3.12
  #          -Dsonar.sources=app
  #          -Dsonar.python.coverage.reportPaths=coverage/coverage.xml
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}